In [1]:
##This is a Jupyter notebook for Linear Algebra HW.
##Belongs to Divya E. Vernerey
##January 2025

In [2]:
!pip install numpy

## Linear Transformations

Let us shift the focus from solving linear systems to the use of matrix algebra to represent maps between vector spaces.  We will see that certain class of useful maps called linear transformations can be described with matrix multiplication.

A **mapping** between vector spaces is a rule that associates input vectors with output vectors.  We say that the input vectors get "mapped" to the output vectors.  The input and output vectors may be in different spaces, or they may be in the same space.  There may be multiple input vectors that get mapped to a single output vector, but it is important that each input vector gets mapped to a unique output vector.  In the language of calculus, mappings are known as functions.


When we refer to a specific map, we might use a symbol, such as $T$.  In order to specify which spaces contain the input and output vectors, say $\mathbb{R}^2$ and $\mathbb{R}^3$, we write $T: \mathbb{R}^2 \to \mathbb{R}^3$.  This notation means that $T$ is a mapping that takes vectors in $\mathbb{R}^2$ as inputs, and maps them to vectors in $\mathbb{R}^3$.  When we refer to the output associated with a specific vector, say $V$, we use the notation $T(V)$.  (*This notation is read "$T$ of $V$".  The reader familiar with calculus will recognize the notation as that commonly used with functions.*).  Finally, if we wish to label the output vector as $W$, we will write $T(V)=W$, meaning that the input vector $V$ gets mapped to the output vector $W$ by the map $T$.  The vector $W$ is said to be the **image** of $V$ under the map $T$.  Similarly, the vector $V$ is said to be the **preimage** of $W$.

### Example 1:  Transformation from $\mathbb{R}^2$ to $\mathbb{R}^3$

A Python function that accepts one vector as an argument, and provides one vector in return, is a perfect model of a mapping.  As an example, let's write a function that accepts a vector from $\mathbb{R}^2$ and returns a vector in $\mathbb{R}^3$.

In [3]:
import numpy as np

def T(V):
    W = np.zeros((3,1))  #Creating an array of rowSize: 3, and columnSize: 1 that all contain "0"
    W[0,0] = 2*V[0,0] #Multiplying v1 by "2" to get "2v1" and storing it in the zeroth index of "W"
    W[2,0] = V[1,0] #Storing v2 into second index of "W"
    return W

V = np.array([[3],[5]])  #Creating Array "V" with 2 rows and 1 column, that is defining v1 as "3" and v2 as "5"
W = T(V)

print(V,'\n\n',W)

[[3]
 [5]] 

 [[6.]
 [0.]
 [5.]]


We can describe this mapping $T:\mathbb{R}^2 \to \mathbb{R}^3$ with the following symbolic formula.

$$
\begin{equation}
T \left(\left[\begin{array}{r} v_1 \\ v_2 \end{array} \right]\right) =
\left[\begin{array}{r} 2v_1 \\ 0  \\ v_2 \end{array} \right]
\end{equation}
$$



### Linearity

A map $T$ is said to be *linear* if the following two properties are true for any scalar $k$, and any input vectors $U$ and $V$.  

- $T(kV)$ = $kT(V)$
- $T(U + V)$ = $T(U) + T(V)$

A linear map is referred to as a **linear transformation**.

The map $T$ in **Example 1** is a linear transformation.  

$$
\begin{eqnarray*}
T(kV)  = T \left(\left [\begin{array}{r} kv_1 \\ kv_2 \end{array} \right]\right) & = &
\left[\begin{array}{r} 2kv_1 \\ 0  \\ kv_2 \end{array} \right] =
k\left[\begin{array}{r} 2v_1 \\ 0  \\ v_2 \end{array} \right] = kT(V)\\
\\
T(U+V) = T \left(\left [\begin{array}{r} u_1 + v_1 \\ u_2 + v_2 \end{array} \right]\right) & = &
\left[\begin{array}{r} 2u_1 \\ 0  \\ u_2 \end{array} \right] +
\left[\begin{array}{r} 2v_1 \\ 0  \\ v_2 \end{array} \right] = T(U) + T(V)
\end{eqnarray*}
$$

If we choose specific vectors $U$ and $V$, and a specific scalar $k$, we can compute the left and right sides of these equations with syntax that matches the notation

In [4]:
U = np.array([[-1],[3]])
V = np.array([[3],[5]])
k = 7
print(T(k*V),'\n')
print(k*T(V),'\n')
print(T(U+V),'\n')
print(T(U)+T(V))

[[42.]
 [ 0.]
 [35.]] 

[[42.]
 [ 0.]
 [35.]] 

[[4.]
 [0.]
 [8.]] 

[[4.]
 [0.]
 [8.]]


Showing these equations hold for a *specific choice* of $U$, $V$, and $k$ does not prove that the transformation is linear.  Even if we were to run this code inside a loop and see that the equations held for a million random combinations of $U$, $V$, and $k$, that would still not *prove* that the transformation is linear.  It would however provide numerical evidence to support the claim.  

### Example 2:  Transformation defined as matrix multiplication

Let $L:\mathbb{R}^3 \to \mathbb{R}^3$ be defined by $L(X)= AX$ where $A$ is the following matrix.

$$
\begin{equation}
A = \left[\begin{array}{rrr} 1 & 1 & 0 \\ 1 & 0 & 2 \\ 3 & 1 & -1 \end{array}\right]
\end{equation}
$$

Since matrix multiplication is linear, a transformation defined by matrix multiplication is linear as well.  If $X$ and $Y$ are any vectors in $\mathbb{R}^3$, and $k$ is any scalar, then $L(X+Y) = A(X+Y) = AX + AY = L(X) + L(Y)$ and $L(kX) = A(kX) = k(AX) = kL(X)$.  We define a function for this transformation as well.

In [5]:
def L(V):
    A = np.array([[1,1,0],[1,0,2],[3,1,-1]]) #Create an Array A
    W = A@V #Multiplying the two matrix
    return W

V = np.array([[1],[3],[5]])
W = L(V)

print(V,'\n\n',W)

[[1]
 [3]
 [5]] 

 [[ 4]
 [11]
 [ 1]]


### Example 3:  Transformation from $\mathbb{P}^3$ to $\mathbb{P}^5$

In this final example we consider a transformation between vector spaces of polynomials.  We can define a linear transformation $M:\mathbb{P}_3\to\mathbb{P}_5$ by multiplying by some fixed quadratic polynomial, say $x^2 + 2$.  Let's write out the formula for $M$ by calculating $M(P)$ for an arbitrary $P = a_3x^3 + a_2x^2 + a_1x + a_0$.

$$
\begin{eqnarray*}
M(P) & = & (x^2 + 2)(a_3x^3 + a_2x^2 + a_1x + a_0) \\
     & = & a_3x^5 + a^2x^4 + (2a_3 + a_1)x^3 + (2a_2 + a_0)x^2 + 2a_1x + 2a_0
\end{eqnarray*}
$$

This transformation must be linear by the algebraic rules for multiplication.  If $P$ and $Q$ are any polynomials in $\mathbb{P}^3$ and $k$ is any scalar, we know that $M(P+Q) = (x^2+2)(P+Q) = (x^2+2)P + (x^2+2)Q = M(P) + M(Q)$, and $M(kP) = (x^2+2)(kP) = k[(x^2+2)P] = kM(P)$.

### Compositions

If two transformations are to be applied, one after the other, it is common to combine them to form what is known as a **composition**.  This idea only makes sense when the output space of the first transformation matches the input space of the second.  In symbols, if $T:\mathbb{U}\to\mathbb{V}$ and $L:\mathbb{V}\to\mathbb{W}$, then we could consider the composition $L\circ T:\mathbb{U}\to\mathbb{W}$.  The notation $L\circ T$ represents the composition formed by applying the map $T$, followed by the map $L$.

As an example, if we take $T:\mathbb{R}^2 \to \mathbb{R}^3$ and $L:\mathbb{R}^3 \to \mathbb{R}^3$ to be the transformations defined in **Example 2** and **Example 3**, we could define $L\circ T:\mathbb{R}^2 \to \mathbb{R}^3$.

$$
\begin{equation}
(L\circ T)\left(\left[\begin{array}{r} v_1 \\ v_2 \end{array} \right]\right) =
\left[\begin{array}{rrr} 1 & 1 & 0 \\ 1 & 0 & 2 \\ 3 & 1 & -1 \end{array}\right]
\left[\begin{array}{r} 2v_1 \\ 0  \\ v_2 \end{array} \right]
\end{equation}
$$

We can calculate outputs from this transformation by calling the functions we defined earlier *in the appropriate order*, using the output from $T$ as the input to $L$.

In [6]:
V = np.array([[3],[5]])
composition_output = L(T(V))
print(composition_output)

[[ 6.]
 [16.]
 [13.]]


### Exercises

**Exercise 1:** Find the vector $T(V)$ where

$$
\begin{equation}
V = \left[\begin{array}{r} 1 \\ 3 \end{array} \right]
\end{equation}
$$

In [7]:
## Code solution here.
V = np.array([[1],[3]])  #Creating Array "V" with 2 rows and 1 column, that is defining v1 as "1" and v2 as "3"
W = T(V)

print(W)

[[2.]
 [0.]
 [3.]]


**Exercise 2:** Find the vector $U$ so that

$$
\begin{equation}
T(U) = \left[\begin{array}{r} 5 \\ 0 \\ -1 \end{array} \right]
\end{equation}
$$

In [8]:
## Code solution here.
U = np.array([[5],[0],[-1]])  
W = T(V)
print(W)

[[2.]
 [0.]
 [3.]]


**Exercise 3:**  Write a Python function that implements the transformation $N:\mathbb{R}^3\to\mathbb{R}^2$, given by the following rule.  Use the function to find evidence that $N$ is **not linear**.

$$
\begin{equation}
N \left(\left[\begin{array}{r} v_1 \\ v_2 \\ v_3 \end{array} \right]\right) =
\left[\begin{array}{c} 8v_2 \\  v_1 + v_2 + 3 \end{array} \right]
\end{equation}
$$

In [9]:
## Code solution here.
## Code solution here.
import numpy as np

def N(V):
    W = np.zeros((2,1)) 
    W[0,0] = 8*V[1,0] 
    W[1,0] = V[0,0]+V[1,0]+3 
    return W

#proof that it is not linear
U = np.zeros((3,1)) 
U[0,0] = 3
U[1,0]= 2
U[2,0] = 1
V = np.zeros((3,1))
V[0,0] = 50
V[1,0] = 60
V[2,0] = 40

print (N(U) ,'\n')
print (N(V), '\n')
print (N(U+V), '\n')
#if it is not linear, when multiplying by a scalar quantity it will not be equal. Additionally, n(u+v) where u and v are 2 vectors has to be equal to n(u) + n(v).
#for example if we pick the first array of [1,2,3], and then another array of [3,4,5] (3 rows 1 column), when we run the example we will see that it is different.
#Because 113 + 8 does not equal 121, this is not linear

[[16.]
 [ 8.]] 

[[480.]
 [113.]] 

[[496.]
 [118.]] 



**Exercise 4:**  Consider the two transformations, $S$ and $R$, defined below.  Write a Python function that implements the composition $R\circ S$.  Explain why it is not possible to form the composition $S \circ R$.

$$
\begin{equation}
S \left(\left[\begin{array}{r} v_1 \\ v_2 \\ v_3 \end{array} \right]\right) =
\left[\begin{array}{c}   v_1 + v_2 \\  3v_3 \end{array} \right]
\end{equation}
$$

$$
\begin{equation}
R \left(\left[\begin{array}{r} v_1 \\ v_2  \end{array} \right]\right) =
\left[\begin{array}{rr} 3 &  0 \\ -1 & 1 \end{array}\right]
\left[\begin{array}{c}   v_1 \\ v_2 \end{array} \right]
\end{equation}
$$
  

In [10]:
## Code solution here.
def S(V):
    W = np.zeros((2,1))
    W[0,0] = V[0,0] 
    W[1,0] = 3@V[2,0]
    return W

def R(V):
    C = np.zeros((2,2))
    C[0,0] = 3
    C[1,0] = -1
    C[0,1] = 0
    C[1,1] = 1
    
    W = np.zeros((2,1))
    W[0,0] = V[0,0]
    W[1,0] = V[1,0]

    return C@W

def ComposeV(V):
    return R(S(V))

#It is not possible to form the composition becuase the number of Columns in S would not match the number of rows in R.

**Exercise 5:** Create a Python function which implements the transformation: $S:\mathbb{R}^3\to\mathbb{R}^3$, given below. Use the function to provide evidence whether the transformation is **linear** or not.


$$
\begin{equation}
S \left(\left[\begin{array}{r} v_1 \\ v_2 \\ v_3 \end{array} \right]\right) =
\left[\begin{array}{c} v_1 + v_2 \\  1 \\ v_3+v_1 \end{array} \right]
\end{equation}
$$

Repeat for the transformation $T:\mathbb{R}^3\to\mathbb{R}^3$ is now defined by

$$
\begin{equation}
T \left(\left[\begin{array}{r} v_1 \\ v_2 \\ v_3 \end{array} \right]\right) =
\left[\begin{array}{c} v_1 + v_2 \\  0 \\ v_3+v_1 \end{array} \right].
\end{equation}
$$

In [11]:
## Code solution here
import numpy as np

def S(V):
    W = np.zeros((3,1)) 
    W[0,0] = V[0,0] + V [1,0]
    W[1,0] = 1
    W[2,0] = V[2,0] + V[0,0] 
    return W

# Test case input  
U = np.zeros((3,1)) 
U[0,0] = 3
U[1,0]= 2
U[2,0] = 1
V = np.zeros((3,1))
V[0,0] = 50
V[1,0] = 60
V[2,0] = 40

print (S(U) ,'\n')
print (S(V), '\n')
print (S(U+V), '\n')
print (S(U)+S(V),'\n')

def T(V):
    W = np.zeros((3,1)) 
    W[0,0] = V[0,0] + V [1,0]
    W[1,0] = 0
    W[2,0] = V[2,0] + V[0,0] 
    return W

# Test case input  
print (R(U) ,'\n')
print (R(V), '\n')
print (R(U+V), '\n')
print (R(U)+R(V),'\n')

#Based on the data, we can see that s is not linear and b is linear (See question 3 for explanation of test case). 

[[5.]
 [1.]
 [4.]] 

[[110.]
 [  1.]
 [ 90.]] 

[[115.]
 [  1.]
 [ 94.]] 

[[115.]
 [  2.]
 [ 94.]] 

[[ 9.]
 [-1.]] 

[[150.]
 [ 10.]] 

[[159.]
 [  9.]] 

[[159.]
 [  9.]] 



**Exercise 6:** $L:\mathbb{R}^3\to\mathbb{R}^2$ is a **Linear Transformation** . Find $L(kU+V)$ given that $k=7$,

$$
\begin{equation}
L(U) = \left[\begin{array}{r} 1 \\ 1  \end{array} \right]\hspace{1cm}
L(V) = \left[\begin{array}{r} 3 \\ 1  \end{array} \right]
\end{equation}
$$

In [12]:
## Code solution here
#L(kU) = kL(U)
# we know that k = 7
# We can apply L(kU) + L(V)
# The final tranformation will be kL(U) + L(V) 

import numpy as np
L_U = np.array([[1], [1]])
L_V = np.array([[3], [1]])
k = 7
result = k * L_U + L_V
print(result)

[[10]
 [ 8]]


**Exercise 7:** Let $T:\mathbb{R}^3 \to \mathbb{R}^2$ be defined by $T(X)= AX$, where

$$
\begin{equation}
A = \left[\begin{array}{rrr} 1 & 0 & 2 \\ 2 & 1 & 1  \end{array}\right].
\end{equation}
$$

Find all vectors $X$ that satisfy $T(X) = \left[\begin{array}{r} 1 \\ 2  \end{array} \right]
$.


In [13]:
## Code solution here
## Our goal is to find X

def T(X):
    A = np.array([[1, 0, 2],[2, 1, 1]])
    b = np.array([[3],[6], [2]])
    A.dot(X)

**Exercise 8:** Let $M:\mathbb{P}_1 \to \mathbb{P}_3$ be a transformation defined by $M(p(x)) = x^3 + p(x)$. Determine whether $M$ is linear or not.

In [14]:
## Code solution here
## Goal, see if M is linear or not when M is P1 -> P3 
import numpy as np

def M(x): 
    A = np.zeros((1,4))
    A[0,0] = 1
    A[0,1] = 0
    A[0,2] = x[0] 
    A[0,3] = x[1] 
    return A

V = np.array([2,4])

print("V:\n", V, '\n')
print("M(2V):\n", M(2 * V), '\n') 
print("M will not be linear.") 

V:
 [2 4] 

M(2V):
 [[1. 0. 4. 8.]] 

M will not be linear.
